### PR TITLE
Use ADAFLAGS CFLAGS CPPFLAGS LDFLAGS when available

### PR DESCRIPTION
**Pull request by asarhaddon**
Please let the GNAT projects use the usual variables if available in the environment.
Thanks.

### CODE REVIEW

**Comment by asarhaddon** [comment]
Hello.
I see that 21.0 is on its way, and modifies the projects.
I would like to know if these changes are of any interest to you before investing time in rebasing them.
Thanks.

**Comment by Fabien-Chouteau** [comment]
Hello @asarhaddon, sorry for the late reply.

Instead of changing the project files you can use the `-cargs`, `-largs` options in gprbuild: https://docs.adacore.com/gprbuild-docs/html/gprbuild_ug/building_with_gprbuild.html?highlight=cargs#command-line

**Comment by asarhaddon** [comment]
Thanks for your answer.
I prefer to avoid `-cargs $(ADAFLAGS)` because it is unspecified how gprbuild mixes for example `-cargs -O0` and `for Compiler.Switches ("ada") use ("-O2")`.
Moreover, for redistributors like me CFLAGS/LDFLAGS/.. are computed automatically depending on the build context and set in the environment by the build system. My task is significantly more complex if I have to construct a line like `make GPRBUILD_OPTIONS='-gnatc $(ADAFLAGS) -gnatl $(LDFLAGS) -bargs'.
The makefiles for gnatcoll-db offer such a mechanism, but in most projects a patch is necessary, or local default values are added *after* GPRBUILD_OPTIONS, overriding them. Even once the mechanism exists, the value for ADAFLAGS is expanded in various ways by several shell and make instances. Escaping an unpredictable space-encoded list properly quickly becomes a nightmare.
All this work disappears if the project directly reads the environment, and explicitly encodes the flag precedence.

**Comment by asarhaddon** [comment]
Hello.
I have reordered the patch queue for easyer review.
The third commit fixes two build failures for the sqlite component.

**Comment by t-14** [comment]
Thank you for your contribution.

**Pull request merged**
